export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST'
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS'
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE'

export const SELECT_REPO = 'SELECT_REPO'

export const FETCH_CONTRIBUTORS_REQUEST = 'FETCH_CONTRIBUTORS_REQUEST'
export const FETCH_CONTRIBUTORS_SUCCESS = 'FETCH_CONTRIBUTORS_SUCCESS'
export const FETCH_CONTRIBUTORS_FAILURE = 'FETCH_CONTRIBUTORS_FAILURE'
